#include "ucx.h"

const int routing_table_size = 12;

const ERROR_ACTION_TYPE hm_table_partition_1[4][4] = {
    // Colonnes : DEADLINE_MISSED, APPLICATION_ERROR, NUMERIC_ERROR, DEFAULT
    
    // Ligne 0 : État IDLE
    {  PROCESS_RESTART, PROCESS_STOP, PARTITION_RESTART, PROCESS_STOP },

    // Ligne 1 : État COLD_START
    {  PROCESS_RESTART, PROCESS_STOP, PARTITION_RESTART, PROCESS_STOP },

    // Ligne 2 : État WARM_START
    {  PROCESS_RESTART, PROCESS_STOP, PARTITION_RESTART, PROCESS_STOP },
    
    // Ligne 3 : État NORMAL
    { IGNORE, PROCESS_STOP, PROCESS_RESTART, PROCESS_STOP }
};

const ERROR_ACTION_TYPE hm_table_partition_2[4][4] = {
    // Colonnes : DEADLINE_MISSED, APPLICATION_ERROR, NUMERIC_ERROR, DEFAULT
    
    // Ligne 0 : État IDLE
    {  PROCESS_RESTART, PROCESS_STOP, PARTITION_RESTART, PROCESS_STOP },

    // Ligne 1 : État COLD_START
    {  PROCESS_RESTART, PROCESS_STOP, PARTITION_RESTART, PROCESS_STOP },

    // Ligne 2 : État WARM_START
    {  PROCESS_RESTART, PROCESS_STOP, PARTITION_RESTART, PROCESS_STOP },
    
    // Ligne 3 : État NORMAL
    { PROCESS_REPLENISH, PROCESS_STOP, PROCESS_RESTART, PROCESS_STOP }
};

const ERROR_ACTION_TYPE hm_table_module[1][4] = {
    // Colonnes : DEADLINE_MISSED, APPLICATION_ERROR, NUMERIC_ERROR, DEFAULT
    
    // // Ligne 0 : État IDLE
    // {  PROCESS_RESTART, PROCESS_STOP, PARTITION_RESTART, PROCESS_STOP },

    // // Ligne 1 : État COLD_START
    // {  PROCESS_RESTART, PROCESS_STOP, PARTITION_RESTART, PROCESS_STOP },

    // // Ligne 2 : État WARM_START
    // {  PROCESS_RESTART, PROCESS_STOP, PARTITION_RESTART, PROCESS_STOP },
    
    // Ligne 3 : État NORMAL
    { PROCESS_REPLENISH, PROCESS_STOP, PROCESS_RESTART, PROCESS_STOP }
};
